; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
upload_speed = 460800
lib_deps =
    adafruit/Adafruit GFX Library@^1.11.9
    2dom/PxMatrix LED MATRIX library@^1.8.2

; OTA прошивка по WiFi:
upload_protocol = espota
upload_port = 192.168.31.81
